### ISSUE TITLE
issue after interval cap was meet

### ISSUE THREAD

**Issue by czxyang** [kmcroft13/traverse-box-items#1]
Hi 

i have issue regarding this interval cap in the queue.
i use the csv as source and set interval cap to 3, after running the code the script logs show below (it seems like after interval cap was meet, and queue went repeat use last row data 167491346442 in the csv)

```
2019-03-22T15:37:36.929Z	INFO	d5zec22aktc00	getFileInfo	RETRIEVE_FILE_INFO	retrieved info for file 21913383623	
2019-03-22T15:37:37.023Z	INFO	gdjilvjdbrk00	getFileInfo	RETRIEVE_FILE_INFO	retrieved info for file 238489060245	
2019-03-22T15:37:37.070Z	INFO	2hiqsjny4n20	getFileInfo	RETRIEVE_FILE_INFO	retrieved info for file 4209103060	
2019-03-22T15:37:37.242Z	INFO	a62789jik4k00	getFileInfo	PREPARE_FILE_INFO	**Getting info for file 167491346442	
2019-03-22T15:37:37.242Z	INFO	a62789jik4k00	getFileInfo	PREPARE_FILE_INFO	Getting info for file 167491346442	
2019-03-22T15:37:37.242Z	INFO	a62789jik4k00	getFileInfo	PREPARE_FILE_INFO	Getting info for file 167491346442	
2019-03-22T15:37:37.480Z	INFO	k07gfl15lto00	getFileInfo	RETRIEVE_FILE_INFO	retrieved info for file 167491346442	
2019-03-22T15:37:37.491Z	INFO	55q1dhx52to00	getFileInfo	RETRIEVE_FILE_INFO	retrieved info for file 167491346442	
2019-03-22T15:37:37.551Z	INFO	enm57pm2r9s00	getFileInfo	RETRIEVE_FILE_INFO	retrieved info for file 167491346442**
```

do you have a fix for this?

**Comment by kylepinecroft** [comment]
@czxyang Thanks for reaching out! I'll take a look. Can you post your config file contents (except leaving out the `boxSettings` section at the bottom)?

**Comment by czxyang** [comment]
Hi

here is my config file content

```json
{
  "modifyData": true,
  "auditTraversal": true,
  "maxConcurrentUsers": 10,
  "maxQueueTasksPerSecond": 3,
  "nonOwnedItems": {
    "skip": true,
    "audit": false
  },
  "csv": {
    "enabled": true,
    "filePath": "C:\\open_links.csv"
  },
  "blacklist": {
    "enabled": false,
    "users": [""],
    "folders": [""]
  },
  "whitelist": {
    "enabled": false,
    "items": [
      {
        "ownerID": "",
        "folderIDs": [""],
        "followAllChildItems": false
      }
    ]
  },
  "userDefinedConfigs": {
    "matchSharedLinkAccessLevel":"open",
    "newSharedLinkAccessLevel":"company"
  },
  "boxItemFields": "id,name,type,created_at,modified_at,path_collection,shared_link,owned_by,size",
  "boxAppSettings": {
    "clientID": "",
    "clientSecret": "",
    "appAuth": {
      "keyID": "",
      "privateKey": "",
      "passphrase": ""
  },
    "enterpriseID": ""
  }
}
```

**Comment by kylepinecroft** [comment]
@czxyang I wasn't able to reproduce this issue using your configured options, unfortunately. However I did make some logging enhancements that might helps us identify the issue. Can you download / pull the latest version and give that a try?

If you choose to re-use your old configuration file rather than use the config file that comes with the new download / pull, please be sure to add the new `logLevel` config property. In either case, set it to "debug" for test purposes so that we can get the detailed messages for troubleshooting.

Please share the results of the debug logs once you have them!

**Comment by czxyang** [comment]
@kmcroft13 thanks getting me back, i was able by pass the error using your other branch.
but i found something else in line 434 userCache[ownerId].queue.add( async function() { await getFileInfo(fileID, parentExecutionID) }); should getfileInfo also taking owerId as param?

and in your User define example code line 140 cache.push(`getItemInfo|file:${fileID}|user:${clientUserObj.id}`); this does not seem right, what is cache shoulda be queue.add and the function modifySharedLink?

here are the errors im getting now

{"statusCode":400,"body":{"error":"**invalid_grant**","error_description":"Please check the 'jti' claim. A unique 'jti' value is required."},"headers":{"date":"Sun, 24 Mar 2019 21:54:22 GMT","content-type":"application/json","content-length":"111","connection":"keep-alive","cache-control":"no-store","vary":"Accept-Encoding","strict-transport-security":"max-age=31536000","set-cookie":["box_visitor_id=5c97fc8de42339.10341055; expires=Tue, 24-Mar-2020 21:54:21 GMT; Max-Age=31622400; path=/; domain=.box.com; secure","bv=OPS-42942; expires=Sun, 31-Mar-2019 21:54:21 GMT; Max-Age=604800; path=/; domain=.app.box.com; secure","cn=10; expires=Tue, 24-Mar-2020 21:54:21 GMT; Max-Age=31622400; path=/; domain=.app.box.com; secure","site_preference=desktop; path=/; domain=.box.com; secure"],"age":"0"},"request":{"uri":{"protocol":"https:","slashes":true,"auth":null,"host":"api.box.com","port":443,"hostname":"api.box.com","hash":null,"search":null,"query":null,"pathname":"/oauth2/token","path":"/oauth2/token","href":"https://api.box.com/oauth2/token"},"method":"POST","headers":{"User-Agent":"Box Node.js SDK v1.22.0 (Node v10.15.1)","content-type":"application/x-www-form-urlencoded","accept":"application/json","content-length":815}}}

{"errno":"**ENOBUFS**","code":"ENOBUFS","syscall":"connect","address":"107.152.27.197","port":443,"request":{"uri":{"protocol":"https:","slashes":true,"auth":null,"host":"api.box.com","port":null,"hostname":"api.box.com","hash":null,"search":"?fields=id%2Cname%2Ctype%2Ccreated_at%2Cmodified_at%2Cpath_collection%2Cshared_link%2Cowned_by%2Csize","query":"fields=id%2Cname%2Ctype%2Ccreated_at%2Cmodified_at%2Cpath_collection%2Cshared_link%2Cowned_by%2Csize","pathname":"/2.0/folders/5198909325","path":"/2.0/folders/5198909325?fields=id%2Cname%2Ctype%2Ccreated_at%2Cmodified_at%2Cpath_collection%2Cshared_link%2Cowned_by%2Csize","href":"https://api.box.com/2.0/folders/5198909325?fields=id%2Cname%2Ctype%2Ccreated_at%2Cmodified_at%2Cpath_collection%2Cshared_link%2Cowned_by%2Csize"},"method":"GET","headers":{"User-Agent":"Box Node.js SDK v1.22.0 (Node v10.15.1)","Authorization":"[REMOVED BY SDK]","X-Box-UA":"agent=box-node-sdk/1.22.0; env=Node/10.15.1","host":"api.box.com","accept":"application/json"}},"maxRetriesExceeded":true}

do you know what can cause those errors?

Thanks
please advise.

**Comment by kylepinecroft** [comment]
@czxyang Good catches, thanks for pointing those out. The first was just a bug on my part and the second was leftover from an old implementation of queuing that I was using before refactoring to the current (more robust) queueing method. Both issues have been fixed and pushed (along with another minor enhancement I've been working on).

As for the specific error you're seeing now, this is returned by the underlying Box Node SDK and isn't necessarily an issue with this particular script. It is almost certainly caused by hitting rate limits during token retrieval.
If you keep the `maxQueueTasksPerSecond` at 16 or below (Box's default rate limit) you _shouldn't_ run into this issue. Are you still using a value of 3 in this case like you were previously?

**Comment by czxyang** [comment]
@kmcroft13 thanks for the update, i was running at maxQueueTasksPerSecond = 10 when i got those errors.
i will pull down the newer version and try to run it with a lower setting.

Thanks
